# Generated by Django 4.2.3 on 2023-07-31 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharactersList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('birth', models.CharField(max_length=255, null=True)),
                ('death', models.CharField(max_length=255, null=True)),
                ('age', models.IntegerField(null=True)),
                ('is_alive', models.BooleanField()),
                ('country', models.CharField(max_length=50, null=True)),
                ('charactersList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.characterslist')),
            ],
        ),
    ]
