# Generated by Django 4.2.3 on 2023-08-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_alter_characterslist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.FileField(null=True, upload_to='public'),
        ),
    ]
