# Generated by Django 4.2.3 on 2023-08-05 17:36

from django.db import migrations
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_character_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='private_image',
            field=private_storage.fields.PrivateFileField(null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='private'),
        ),
    ]
